### ISSUE TITLE
GitFileTree-MergeDriver Windows

### ISSUE THREAD

**Issue by marcelja** [HPI-SWA-Teaching/Squeak-DemoMode#6]
Den GitFileTree-MergeDriver sollten wir unter Windows zum Laufen bringen, damit wir auch gleichzeitig den Code bearbeiten können.

**Comment by marcelja** [comment]
make (e=2): Das System kann die angegebene Datei nicht finden.
makefile:4: recipe for target 'pharo/Pharo.image' failed
make: **\* [pharo/Pharo.image] Error 2

bekomme auch diesen Fehler...

**Comment by b-feldmann** [comment]
gleicher Fehler bei mir
