### ISSUE TITLE
Travis-Ci Test - enterDemoModeTest schlägt fehl

### ISSUE THREAD

**Issue by b-feldmann** [HPI-SWA-Teaching/Squeak-DemoMode#7]
Direkt im Image funktionieren alle Tests einwandfrei - bei Travic-Ci jedoch nicht.

Möglicherweise ist die Nachricht _setDemoFonts_ der Klasse _Preferences_ nicht im Travis-Ci Image enthalten.
- [x] Test läuft lokal durch
- [x] Überprüfen ob die Nachricht im Travis Image enthalten ist.
- [x] Wenn nicht dann eigene Methode schreiben (copy von setDemoFonts)

**Comment by marcelja** [comment]
ich glaube, das liegt doch nicht an setDemoFonts (habe das auskommentiert und klappt nicht)

**Comment by b-feldmann** [comment]
mhmm okay.. na ich guck mir das morgen abend nochmal an..

**Comment by marcelja** [comment]
ist eigentlich auch erstmal egal^^

**Comment by b-feldmann** [comment]
hast du die Methode einfach nur kopiert?
Meine setDemoFonts Methode sieht komplett anders aus O.o

**Comment by marcelja** [comment]
erst hatte ich sie nur kopiert und dann nochmal anders geschrieben.

**Comment by marcelja** [comment]
müsste an "UIManager default restoreDisplay" liegen.
mit "World restoreMorphicDisplay" geht es wahrscheinlich.
